# Generated by Django 2.2.3 on 2019-08-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190802_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='published_date',
        ),
    ]
