# Generated by Django 2.2.3 on 2019-08-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_feedback_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
