# Generated by Django 2.2.3 on 2019-08-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190803_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='gatepass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField()),
                ('branch', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('contact_number', models.IntegerField()),
                ('purpose_of_visit', models.TextField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('entry_time', models.CharField(max_length=20)),
                ('exit_time', models.CharField(max_length=20)),
            ],
        ),
    ]
