# Generated by Django 2.2.3 on 2019-08-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_gatepass_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='father_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
