# Generated by Django 2.2.3 on 2019-08-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_gatepass_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='father_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='photos'),
        ),
    ]
