# Generated by Django 2.2.3 on 2019-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190805_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='photos'),
        ),
    ]
