# Generated by Django 2.2.3 on 2019-08-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190805_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image/'),
        ),
    ]
