# Generated by Django 2.2.3 on 2019-08-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190803_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
