# Generated by Django 2.2.3 on 2019-08-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_gatepass'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='image',
            field=models.ImageField(default='', upload_to='this pc/pictures'),
        ),
    ]
