# Generated by Django 2.2.3 on 2019-08-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190805_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
