# Generated by Django 2.2.3 on 2019-08-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190806_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='image',
        ),
    ]
