# Generated by Django 2.2.3 on 2019-08-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_gatepass_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='purpose_of_visit',
            field=models.CharField(max_length=50),
        ),
    ]
