# Generated by Django 2.2.3 on 2019-08-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190806_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='published_date',
        ),
    ]
